### PR TITLE
Adding a convenience method for easier enum (sealed type) codec registration

### PR DESCRIPTION
**Pull request by jakrawcz-rdx**
A follow-up to https://github.com/radixdlt/babylon-node/pull/323#issuecomment-1433418441.

### CODE REVIEW

**Comment by jakrawcz-rdx** [comment]
@dhedey after this PR, very large parts of `EnumEntry, Fields, StructCodec & co` become 3735929054 (base 16).
I would seriously consider removing them (or rather, reducing to a very small and not-necessarily-so-convenient API that allows for implementing a very custom codec if ever really needed). I like deleting code, just give me a 🟢.

**Comment by dhedey** [comment]
> @dhedey after this PR, very large parts of `EnumEntry, Fields, StructCodec & co` become 3735929054 (base 16).
> I would seriously consider removing them (or rather, reducing to a very small and not-necessarily-so-convenient API that allows for implementing a very custom codec if ever really needed). I like deleting code, just give me a 🟢.

I wish I'd realised how easy it would have been to create these codecs with modern Java before creating them all, because man was it painful to write all those variants ;)

As much as it pains me, I'm happy for them to be removed, as long as it's possible to create the custom codecs (but as you say, a slightly less convenient API would be fine then 👍)

**Comment by jakrawcz-rdx** [comment]
> I'm happy for them to be removed

That is going to be a future PR, for some other time when I need break from a more serious task 👍 

Let's merge this one?

**Review by dhedey — APPROVED** [review]
Love this! Thanks again for neatening all this up. It's so nice/easy to add codecs now!

**Pull request merged**
