### PR TITLE
Include ledger header summary (hashes, proposer ts) in all Core API `[/lts]/state/...` responses

### PR DESCRIPTION
**Pull request by jakrawcz-rdx**
This is a remaining part of https://radixdlt.atlassian.net/browse/NODE-563.

I added it to both LTS and non-LTS endpoints - and actually this is the reason why I didn't pull `state_version` into the `LedgerHeaderSummary` (i.e. the LTS endpoints already had `state_version`).

I wondered if the "last proof" DB read-out is costly enough to warrant adding a boolean request flag for that - wdyt guys?

### CODE REVIEW

**Comment by jakrawcz-rdx** [comment]
Ok, after seeing https://github.com/radixdlt/babylon-node/pull/585#discussion_r1285110713 I think we have to choose:

---

**1.** `/state`:
Before this PR:
```
{
  item_a: A,
  item_b: B
}
```

After this PR:

**a)** Version is distinct from header summary:
```
{
  state_version: 1337,
  ledger_header_summary: {
    ledger_hashes: ...,
    proposer_timestamp: ...
  }
  item_a: A,
  item_b: B
}
```

**b)** Moving state_version inside the header summary:
```
{
  ledger_header_summary: {
    state_version: 1337,
    ledger_hashes: ...,
    proposer_timestamp: ...
  }
  item_a: A,
  item_b: B
}
```

**c)** Wrapping state_version and the header summary in a single field:
```
{
  at_ledger_state: {
    state_version: 1337,
    ledger_header_summary: {
      ledger_hashes: ...,
      proposer_timestamp: ...
    }
  }
  item_a: A,
  item_b: B
}
```

And after dealing with ☝️ , it would be cool to also choose an aligned solution to 👇 .

---

**2.** `/lts/state`:

Before this PR:
```
{
  state_version: 1337,
  item_a: A,
  item_b: B
}
```

After this PR:

**a)** (no-op) Do not add header summary fields to LTS responses:
```
{
  state_version: 1337,
  item_a: A,
  item_b: B
}
```

**b)** Version is distinct from header summary:
```
{
  state_version: 1337,
  ledger_header_summary: {
    ledger_hashes: ...,
    proposer_timestamp: ...
  }
  item_a: A,
  item_b: B
}
```

**c)** Copying (it's LTS == cannot move!) state_version inside the header summary:
```
{
  state_version: 1337,
  ledger_header_summary: {
    state_version: 1337,
    ledger_hashes: ...,
    proposer_timestamp: ...
  }
  item_a: A,
  item_b: B
}
```

**Comment by jakrawcz-rdx** [comment]
My vote goes to **1c+2b**.

_UNLESS we do not need this header summary in LTS responses, then **1b+2a**._

**Comment by jakrawcz-rdx** [comment]
After a very small poll, I go with **1c+2b**.

**Review by malexandru-rdx — APPROVED** [review]
LGTM! I also vote for 1c+2b.

My only ever recurring question is if we should also update TS SDK (every time we touch core-api schema or just on release) :)

**Pull request merged**
