### PR TITLE
Fix SafetyState recovery; Add a check that loaded SafetyState belongs to the configured validator

### PR DESCRIPTION
**Pull request by LukasGasior1**

### CODE REVIEW

**Review by jakrawcz-rdx — COMMENTED** [review]
I am very happy with the Guice-related changes, but I don't feel qualified to comment on the SafetyStore :(
I know I'd feel more reassured if there was a test showing how SafetyStore didn't work before this change (but ofc, as always - I will totally understand if it's too cumbersome to add at the moment).

**Comment by LukasGasior1** [comment]
Adding a test is quite tricky as the issue was in our main module :man_shrugging:

**Review by jakrawcz-rdx — APPROVED** [review]
Please also get 🟢 from someone more knowledgeable in the SafetyState.

**Comment by LukasGasior1** [comment]
> Please also get 🟢 from someone more knowledgeable in the SafetyState.

I'll note that this will need a retrospective review, but let's get it in for grape

**Review by dhedey — COMMENTED** [review]
Really nice work!

**Pull request merged**
