### PR TITLE
Splitting the validation and preview out of StateManager

### PR DESCRIPTION
**Pull request by jakrawcz-rdx**
This is one of the last steps towards the end goal of https://github.com/radixdlt/babylon-node/pull/407#issuecomment-1511005042.

The immediate un-lock-ing gains come from extracting:
- the `CommitableTransactionValidator` service (i.e. the parse Core API calls no longer lock the `StateManager`)
- the `TransactionPreviewer` service (i.e. the preview Core API calls no longer lock the `StateManager`)

Apart from that, I had to squeeze in a couple of refactors, to make the impls more re-usable/cleaner: in particular, I touched the `TransactionLogic` wrappers a lot.

I still managed to delete more lines than I upsert in this PR, so I feel excused for its large size :p

### CODE REVIEW

**Review by malexandru-rdx — APPROVED** [review]
I don't think this unlocks anything more than before since the contention is still around `StateManageDatabase`, but I like the refactor anyway.

**Comment by jakrawcz-rdx** [comment]
I am seeing strange int-test flakiness:
- `OneNodeFallingBehindTest`
- `FNodesNeverReceiveProposalDropperTest`

They both randomly fail with `LEDGER_IN_ORDER=Optional[TestInvariantError{desc=Two nodes don't agree on transactions}]`. It may be related to my recent changes (not this PR). Investigating.

**Comment by jakrawcz-rdx** [comment]
The `OneNodeFallingBehindTest` cannot fail for me locally at all :(

The `FNodesNeverReceiveProposalDropperTest` fails (locally around ~1/30 runs), sometimes with `LEDGER_IN_ORDER ` assert, but also sometime with a different cause: 
```
# 2023-04-21T09:37:20,844 [INFO/EventLoggerModule/BFT no...yqu0ne6r5] (EventLoggerModule.java:247) - lgr_commit{epoch=1 round=196 version=196 hash=f0ece6f248bd531f user_txns=0}
# 2023-04-21T09:37:20,955 [WARN/LocalSyncService/SyncRunner no...h7gjtsyth] (LocalSyncService.java:450) - LocalSync: Received unexpected sync response from NodeId[025cbdf0646e5db4eaa398f365f2ea7a0e3d419b7e0330e39ce92bddedcac4f9bc]
# 2023-04-21T09:37:21,078 [ERROR/RxModuleRunnerImpl/SyncRunner no...9rgeydvyp] (RxModuleRunnerImpl.java:112) - Unhandled exception in the event processing loop. Shutting down the node.
java.lang.IllegalArgumentException: Tail AccumulatorState{version=192 hash=63deabc564b6000549ac9ee6df2f7590aff40347cf357e904be06383842bc59e} is has lower state version than current AccumulatorState{version=200 hash=997f64b8c4f92e35a151d857279c655ef48947d7705da7a3e5249e780b95e0af}
	at com.radixdlt.ledger.SimpleLedgerAccumulatorAndVerifier.verifyAndGetExtension(SimpleLedgerAccumulatorAndVerifier.java:115) ~[main/:?]
	at com.radixdlt.store.InMemoryTransactionsAndProofReader.getTransactions(InMemoryTransactionsAndProofReader.java:134) ~[testcore/:?]
	at com.radixdlt.sync.RemoteSyncService.getTransactionsWithProofForSyncRequest(RemoteSyncService.java:164) ~[main/:?]
	at com.radixdlt.sync.RemoteSyncService.processSyncRequest(RemoteSyncService.java:136) ~[main/:?]
   ...
```
(my impression is that this ☝️ latter failure mode is a test util `InMemoryTransactionsAndProofReader` problem)

**Comment by jakrawcz-rdx** [comment]
So:
- the first of my recent related changes (https://github.com/radixdlt/babylon-node/pull/420) was simplifying the test util `NetworkDroppers.fNodesAllReceivedProposalsDropped()` (and the flakey `FNodesNeverReceiveProposalDropperTest` happens to use it). However, after rolling back this particular change, I still can repro the flakiness locally. Plus, it isn't used by the other flakey `OneNodeFallingBehindTest`.
- and the second recent change (https://github.com/radixdlt/babylon-node/pull/421) relaxes the locking within java-side `StateComputerLedger. And after rolling it back, this flakiness is gone 😭 Let me investigate and fix it in a separate PR, because this one is definitely unrelated, and mergeable.

**Pull request merged**
